# Generated by Django 3.2 on 2022-01-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20220104_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp85707', max_length=70),
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='deductions',
        ),
        migrations.AddField(
            model_name='payroll',
            name='deductions',
            field=models.ManyToManyField(related_name='payroll', to='management.Deductions'),
        ),
    ]
