# Generated by Django 3.1.7 on 2021-09-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20210908_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='thumb',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp978', max_length=70),
        ),
    ]
