# Generated by Django 3.2 on 2022-01-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_employee_emp_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payroll',
            new_name='GenPayrol',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp278551', max_length=70),
        ),
    ]
