# Generated by Django 3.2 on 2022-01-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20220104_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductions',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='deductions',
            name='description',
            field=models.CharField(default='PAYE', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp166953', max_length=70),
        ),
    ]
