# Generated by Django 3.1.7 on 2021-09-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20210908_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp611', max_length=70),
        ),
    ]
