# Generated by Django 3.2 on 2022-01-04 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20220104_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashadvance',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advance', to='management.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp182475', max_length=70),
        ),
    ]
