# Generated by Django 3.2 on 2022-01-04 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20220104_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp139731', max_length=70),
        ),
        migrations.AlterField(
            model_name='genpayrol',
            name='advance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll', to='management.cashadvance'),
        ),
    ]
