# Generated by Django 3.2 on 2022-01-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20220104_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='deductions',
            name='type',
            field=models.CharField(choices=[('income', 'income'), ('deduction', 'deduction')], default='deduction', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp585786', max_length=70),
        ),
    ]
